version: '3'

services:
  web:
    build: .
    image: maiphuongthao/oc-lettings:latest
    volumes:
      - .:/code
      # - .db.sqlite3
      #static:static
    ports:
      - "8000:8000"
    env_file:
      - .env
