version: '3'

services:
  web:
    image: maiphuongthao/oc-lettings:latest
    volumes:
      - .:/code
      # - .db.sqlite3
      - ./static:/staticfiles
    ports:
      - "8000:8000"
    # environment:
      # - SECRET_KEY=${SECRET_KEY}
      # - SENTRY_DSN=${SENTRY_DSN}
      # - DEBUG=${DEBUG}
