version: '3'

services:
  web:
    build: .
    volumes:
      - .:/code
      # - .db.sqlite3
      #static:static
    ports:
      - "8000:8000"
    secrets:
      - SECRET_KEY
secrets:
  SECRET_KEY:
    file:.env