version: '3'

services:
  web:
    build: .
    image: maiphuongthao/oc-lettings:latest
    # volumes:
      # - .:/code
      # - .db.sqlite3
    ports:
      - "8000:8000"
    # environment:
      # - SECRET_KEY=${SECRET_KEY}
      # - SENTRY_DNS=${SENTRY_DNS}
      # - DEBUG=${DEBUG}
