version: 2.1

orbs:
  docker: circleci/docker@2.4.0

# Define the jobs we want to run for this project
jobs:
  # testing:
    # docker:
      # - image: cimg/python:3.8
        # environment:
          # SECRET_KEY: $SECRET_KEY
          # SENTRY_DNS: $SENTRY_DNS
          # DEBUG: $DEBUG
    # steps:
      # - checkout
      # - run:
          # name: install dependencies
          # command: |
            # python3 -m venv env
            # source env/bin/activate
            # pip install -r requirements.txt
      # - run:
          # name: launch test
          # command: |
            # source env/bin/activate
            # flake8
            # pytest --cov
            # echo "TESTING COMMIT $CIRCLE_SHA1"
# 
  # publish_docker:
    # docker:
      # - image: cimg/python:3.9
        # environment:
          # SECRET_KEY: $SECRET_KEY
          # SENTRY_DNS: $SENTRY_DNS
          # DEBUG: $DEBUG
    # steps:
      # - checkout
      # - setup_remote_docker:
          # version: 20.10.12
      # - run:
          # name: Build and publish Docker image
          # command: |
            # docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            # docker build -t $DOCKER_LOGIN/oc-lettings:$CIRCLE_SHA1 \
            # --build-arg SECRET_KEY=$SECRET_KEY \
            # --build-arg SENTRY_DNS=$SENTRY_DNS \
            # --build-arg DEBUG=$DEBUG \
            # .
            # docker push $DOCKER_LOGIN/oc-lettings:$CIRCLE_SHA1
  deploy_to_aws:
    machine:
      image: ubuntu-2204:2023.07.2
    steps:
      - checkout
      - run:
          name: Test deploy 
          command: |
            ssh $SSH_USER@$SSH_HOST date



workflows:
  build_and_test:
    jobs:
      # - testing
      # - publish_docker
          # requires:
            # - testing
      - deploy_to_aws