version: 2.1


# Define the jobs we want to run for this project
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: configure virtual environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          name: launch pytest
          command: |
            source env/bin/activate
            pytest --cov

# Orchestrate our job run sequence
workflows:
  commit:
    jobs:
      - build_and_test