version: 2.1


# Define the jobs we want to run for this project
jobs:
  testing:
    docker:
      - image: cimg/python:3.8
        environment:
          SECRET_KEY: $SECRET_KEY
    steps:
      - checkout
      - run:
          name: configure virtual environment
          command: |
            python3 -m venv env
            source env/bin/activate
            pip install -r requirements.txt
      - run:
          name: launch pytest
          command: |
            source env/bin/activate
            pytest --cov
            echo "TESTING COMMIT $CIRCLE_SHA1"
  build_image:


# Orchestrate our job run sequence
workflows:
  commit:
    jobs:
      - build_and_test